config/routes.rb
Rails.application.routes.draw do
  get '/@:screen_name' => 'profiles#show_friendly', as: :profile_friendly
  resources :profiles, only: [ :show ]
  resource :profile, only: [ :edit, :update ]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :bots
  post '/rooms/join/:id' => 'rooms#join', as: :join_room
  post '/rooms/leave/:id' => 'rooms#leave', as: :leave_room
  post '/rooms/invite/:id' => 'rooms#invite', as: :invite_room
  get '/r/*screen_name' => 'rooms#show_friendly', as: :room_friendly, screen_name: %r`(?:[a-z0-9_-]+/)?[a-z0-9_-]+`
  resources :rooms
  resources :access_tokens, except: [ :show ]

  root to: 'pages#index'

  # Auth
  get '/auth/:privider/callback' => 'sessions#create'
  post '/auth/:privider/callback' => 'sessions#create'
  get '/sign_out' => 'sessions#destroy', as: :signout

  # API
  mount API::Root => '/api/'
  mount GrapeSwaggerRails::Engine => '/apidoc'

  # ActionCable
  mount ActionCable.server => '/cable'
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :publisher, polymorphic: true
  validates :display_name, presence: true
  validates :screen_name, presence: true, unless: :archived?
  validates :screen_name, format: {
    with: %r`[a-zA-Z0-9_-]+`,
    message: 'screen_name only can contain lowser alphabet and digits, and some symbols(- and _).'
  }
  validates :archived, inclusion: {in: [true, false]}
  validates :screen_name, uniqueness: true
  validates :screen_name, length: { maximum: 64 }

  after_destroy :archive_profile

  attachment :avatar, destroy: false
  has_many :messages

  def archive!
    self.screen_name = nil
    self.archived = true
    self.save
  end

  def type
    publisher_type.downcase.to_sym
  end

  def user?
    type == :user
  end

  def bot?
    type == :bot
  end

  def archived?
    archived
  end

  def user
    publisher if user?
  end

  def bot
    publisher if bot?
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_current_profile, only: [:edit, :update]

  def show
    # for archived profile
    @profile = Profile.find(params[:id])
    authorize @profile
    unless @profile.archived?
      redirect_to profile_friendly_path(@profile.screen_name)
    end
  end

  def show_friendly
    # for not archived profile
    @profile = Profile.find_by(screen_name: params[:screen_name])
    authorize @profile
    if @profile.archived?
      redirect_to profile_path(@profile)
    end
    render action: :show
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: t('Profile was successfully updated.')
    else
      render :edit
    end
  end

  private
  def set_current_profile
    @profile = current_user.profile
    authorize @profile
  end

  def profile_params
    params.require(:profile).permit(:display_name, :screen_name, :avatar)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.slim
.panel.panel-default
  .panel-body
    = simple_form_for(@profile, url: '/profile') do |f|
      = f.error_notification

      .form-inputs
        = f.input :display_name
        = f.input :screen_name
        = f.input :avatar, wrapper: :vertical_input_group do
          = image_tag attachment_url(@profile, :avatar, :fill, 48, 48, format: 'png', fallback: 'default_avatar_48.png')
          = f.input_field :avatar, as: :attachment

      .form-actions
        = f.button :submit

app/views/profiles/edit.html.slim
.row
  .col-sm-6.col-sm-offset-3
    h1 Editing profile
    == render 'form'

app/views/profiles/index.html.slim
h1 Listing profiles

table
  thead
    tr
      th Display name
      th Screen name
      th Avatar
      th Archived
      th
      th
      th

  tbody
    - @profiles.each do |profile|
      tr
        td = profile.display_name
        td = profile.screen_name
        td = profile.avatar_id
        td = profile.archived
        td = link_to 'Show', profile
        td = link_to 'Edit', edit_profile_path(profile)
        td = link_to 'Destroy', profile, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Profile', new_profile_path

app/views/profiles/show.html.slim
.row
  .col-sm-10.col-sm-offset-1
    .profile-card
      .cover
        = image_tag 'https://unsplash.it/950/500/?random'
      .avatar
        = image_tag attachment_url(@profile, :avatar, :fill, 120, 120, format: 'png', fallback: 'default_avatar_120.png'), class: 'img-circle'
      .user-info.text-center
        h2
          = @profile.display_name
        = "@#{@profile.screen_name}"
      - if @profile.user?
        .row
          .col-xs-10.col-xs-offset-1.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
            .panel.panel-default
              .panel-heading.text-center
                = t('.rooms')
              ul.list-group
                - @profile.publisher.chattable_rooms.public_rooms.each do |room|
                  li.list-group-item
                    span.badge
                      = room.chattable_users.size
                    = link_to room.display_name, room_path(room)