config/routes.rb
Rails.application.routes.draw do
  get '/@:screen_name' => 'profiles#show_friendly', as: :profile_friendly
  resources :profiles, only: [ :show ]
  resource :profile, only: [ :edit, :update ]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :bots
  post '/rooms/join/:id' => 'rooms#join', as: :join_room
  post '/rooms/leave/:id' => 'rooms#leave', as: :leave_room
  post '/rooms/invite/:id' => 'rooms#invite', as: :invite_room
  get '/r/*screen_name' => 'rooms#show_friendly', as: :room_friendly, screen_name: %r`(?:[a-z0-9_-]+/)?[a-z0-9_-]+`
  resources :rooms
  resources :access_tokens, except: [ :show ]

  root to: 'pages#index'

  # Auth
  get '/auth/:privider/callback' => 'sessions#create'
  post '/auth/:privider/callback' => 'sessions#create'
  get '/sign_out' => 'sessions#destroy', as: :signout

  # API
  mount API::Root => '/api/'
  mount GrapeSwaggerRails::Engine => '/apidoc'

  # ActionCable
  mount ActionCable.server => '/cable'
end

app/models/bot.rb
class Bot < ApplicationRecord

  belongs_to :user
  has_one :profile, as: :publisher
  accepts_nested_attributes_for :profile
  delegate :screen_name, to: :profile, prefix: false, allow_nil: true
  delegate :display_name, to: :profile, prefix: false, allow_nil: true
  delegate :messages, to: :profile, prefix: false, allow_nil: true
  delegate :avatar, to: :profile, prefix: false, allow_nil: true
  has_many :memberships, as: :memberable, dependent: :destroy
  has_many :rooms, through: :memberships

  validates :user, :access_token, :status, presence: true
  validates :access_token, uniqueness: true

  after_destroy :archive_profile

  enum status: {
    enabled: 10,
    disabled: 20
  }

  def name
    display_name
  end

  def self.generate_token
    Digest::SHA256.hexdigest "#{ENV['TOKEN_SALT']}_#{SecureRandom.uuid}"
  end

  def owner? user
    self.user == user
  end

  private
  def archive_profile
    self.profile.archive!
  end

end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  before_action :set_bot, only: [:edit, :update, :destroy]

  def index
    @bots = policy_scope(Bot)
  end

  def new
    @bot = Bot.new
    @bot.build_profile
    authorize @bot
  end

  def create
    @bot = Bot.new(bot_params)
    @bot.access_token = Bot.generate_token
    @bot.user = current_user
    @bot.profile.archived = false
    authorize @bot
    if @bot.save
      redirect_to bots_path, notice: t('Bot was successfully destroyed.')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @bot.update(bot_params)
      redirect_to @bot, notice: t('Bot was successfully updated.')
    else
      render :edit
    end
  end

  def destroy
    @bot.destroy
    redirect_to bots_url, notice: t('Bot was successfully destroyed.')
  end

  protected
  def begin_of_association_chain
    current_user
  end

  private
  def bot_params
    params.require(:bot).permit(:status, profile_attributes: [:display_name, :screen_name])
  end

  def set_bot
    @bot = Bot.find(params[:id])
    authorize @bot
  end

end

app/views/bots/_form.html.slim
.well.well-sm
  = simple_form_for(bot) do |f|
    = f.error_notification
    = f.simple_fields_for :profile_attributes do |pf|
      = pf.input :display_name
      = pf.input :screen_name
    = f.input :status, as: :select, collection: Bot.statuses.keys, include_blank: false
    = f.button :submit, class: 'btn btn-primary'

app/views/bots/edit.html.slim
.page-header
  h1= t('editing_bot')

== render 'form', bot: @bot

.btn-group
  = link_to t('show'), @bot, class: 'btn btn-primary'
  = link_to t('back'), bots_path, class: 'btn btn-default'

app/views/bots/index.html.slim
.page-header
  h1= t('listing_bots')

table.table.table-bordered.table-collapsed
  thead
    tr
      th= t('display_name')
      th.col-sm-2= t('status')
      th.col-sm-2= t('bot_owner')

  tbody
    - @bots.each do |bot|
      tr
        td= link_to bot.screen_name, bot
        td= bot.status
        td= link_to profile_path(bot.user.profile) do
          = image_tag attachment_url(bot.user.profile, :avatar, :fill, 24, 24, format: 'png', fallback: 'default_avatar_24.png')
          '
          = bot.user.display_name

= link_to t('new_bot'), new_bot_path, class: 'btn btn-primary'

app/views/bots/new.html.slim
.page-header
  h1= t('new_bot')

== render 'form', bot: @bot

.btn-group
  = link_to t('back'), bots_path, class: 'btn btn-default'

app/views/bots/show.html.slim
.page-header
  h1= @bot.screen_name


table.table.table-bordered.table-collapsed
  tbody
    tr
      th.col-sm-2= t('display_name')
      td= @bot.screen_name + " (#{@bot.display_name})"
    tr
      th= t('status')
      td= @bot.status
    tr
      th= t('owner')
      td= link_to profile_path(@bot.user.profile) do
        = image_tag attachment_url(@bot.user&.profile, :avatar, :fill, 24, 24, format: 'png', fallback: 'default_avatar_24.png')
        '
        = @bot.user.display_name
    - if @bot.owner? current_user
      tr
        th= t('access_token')
        td
          .input-group.input-group-sm
            input.form-control.input-sm[ type="text" value=@bot.access_token readonly=true ]
            .input-group-btn
              = link_to '#', role: 'menuitem', class: 'btn btn-primary', disabled: 'disabled' do
                = icon :refresh, t('regenerate_access_token')

= link_to '#', class: 'btn btn-block btn-primary' do
  = icon :plus, t('invite_this_bot_to_room')

hr

.btn-group
  = link_to t('edit'), edit_bot_path(@bot), class: 'btn btn-primary'
  = link_to t('back'), bots_path, class: 'btn btn-default'