config/routes.rb
Rails.application.routes.draw do
  get '/@:screen_name' => 'profiles#show_friendly', as: :profile_friendly
  resources :profiles, only: [ :show ]
  resource :profile, only: [ :edit, :update ]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :bots
  post '/rooms/join/:id' => 'rooms#join', as: :join_room
  post '/rooms/leave/:id' => 'rooms#leave', as: :leave_room
  post '/rooms/invite/:id' => 'rooms#invite', as: :invite_room
  get '/r/*screen_name' => 'rooms#show_friendly', as: :room_friendly, screen_name: %r`(?:[a-z0-9_-]+/)?[a-z0-9_-]+`
  resources :rooms
  resources :access_tokens, except: [ :show ]

  root to: 'pages#index'

  # Auth
  get '/auth/:privider/callback' => 'sessions#create'
  post '/auth/:privider/callback' => 'sessions#create'
  get '/sign_out' => 'sessions#destroy', as: :signout

  # API
  mount API::Root => '/api/'
  mount GrapeSwaggerRails::Engine => '/apidoc'

  # ActionCable
  mount ActionCable.server => '/cable'
end

app/models/room.rb
class Room < ApplicationRecord

  validates :screen_name, :display_name, :description, presence: true
  validates :screen_name, length: { in: 1..255 }
  validates :screen_name, uniqueness: true
  validates :screen_name, format: {
    with: %r`(?:[a-z0-9_-]+/)?[a-z0-9_-]+`,
    message: 'screen_name only can contain lowser alphabet and digits, and some symbols(-, _ and /). Only one slash can be contained.'
  }
  validates :display_name, length: { in: 2..64 }
  validates :description, length: { in: 1..1000 }
  validates :private, inclusion: {in: [true, false]}


  has_many :messages
  has_many :memberships
  has_many :users,
    ->{ where memberships: { memberable_type: 'User' } },
    { through: :memberships, source: :user, class_name: 'User' }
  has_many :bots,
    -> { where memberships: { memberable_type: 'Bot' } },
    { through: :memberships, source: :bot, class_name: 'Bot' }

  Membership.authorities.each do |k, v|
    association_name = "#{k}_users".to_sym
    has_many association_name,
      ->{ where memberships: { memberable_type: 'User', authority: v } },
      { through: :memberships, source: :user, class_name: 'User' }
  end

  has_many :chattable_users,
    -> { where memberships: {memberable_type: 'User', authority: [:administrator, :maintainer, :member]}},
    { through: :memberships, source: :user, class_name: 'User' }

  accepts_nested_attributes_for :users

  scope :public_rooms, -> { where private: false }
  scope :private_rooms, -> { where private: true }

  def group_name
    xs = screen_name.split('/')
    if xs.size == 1
      nil
    else
      xs.first
    end
  end

  def channel_name
    screen_name.split('/').last
  end

  def private?
    private
  end

  def public?
    !private?
  end

  def contains? user
    memberships.where(user: user).limit(1).size > 0
  end

  def chattable? user
    # All members except invited can chat
    [:administrator, :maintainer, :member].include? authority(user)
  end

  def authority user
    return nil unless contains? user
    self.memberships.where( user: user ).first.authority.to_sym
  end

  def invited? user
    authority(user) == :invited
  end

  def destroyable? user
    return false unless contains? user
    [:administrator].include? authority(user)
  end

  def maintainable? user
    return false unless contains? user
    [:administrator, :maintainer].include? authority(user)
  end

  def joinable? user
    # User already joined
    return false if chattable? user

    if private?
      # Only invited user can join to the private room
      return invited? user
    else
      return true
    end
  end

  def leaveable? user
    # User not joined
    return false unless contains? user

    # The last user can't leave from a room
    return false if memberships.size == 1

    case authority user
    when :administrator
      # The last administrator can't leave from a room
      administrator_users.size == 1 ? false : true
    when :maintainer
      true
    when :member
      true
    when :invited
      true
    else
      false
    end
  end

  def bot_addable? user
    [:administrator, :maintainer].include? authority(user)
  end

  def kickable? user
    [:administrator, :maintainer].include? authority(user)
  end

  def promotable? user, target
    # Can't promote yourself.
    return false if user == target
    return false unless contains? user

    have_authority = case authority user
    when :administrator
      [:maintainer, :member].include? authority(target)
    when :maintainer
      [:member].include? authority(target)
    when :member
      false
    else
      false
    end
  end

  def demotable? user, target
    # Can't demote yourself.
    return false if user == target

    case authority user
    when :administrator
      [:maintainer].include? authority(target)
    when :maintainer
      false
    when :member
      false
    else
      false
    end
  end

  def invitable? user
    # Anyone can join or be invited on public room
    return true if public?

    # Only Administrator or maintainer can invite in provate room
    [:administrator, :maintainer].include? authority(user)
  end

  def has_member? user
    users.include? user
  end

  def archived?
    # TODO: implement archived or not
    false
  end

  before_validation :bind_default_values

  private
  def bind_default_values
    self.private ||= false
    return
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :set_room_by_screen_name, only: [:show_friendly]

  def create
    @room = Room.new(room_params)
    @room.memberships.build(
      memberable: current_user,
      authority: :administrator
    )
    authorize @room

    # FIXME: error handling
    if @room.save
      redirect_to(room_path(@room), notice: t('rooms.created'))
    else
      render :new
    end
  end

  def new
    @room = Room.new
    authorize @room
  end

  def show_friendly
    if @room.archived?
      redirect_to room_path(@room)
    end
    render action: :show
  end

  def show
    unless @room.archived?
      redirect_to room_friendly_path(@room.screen_name)
    end
  end

  def index
    @rooms = policy_scope(Room).public_rooms
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: t('Room was successfully updated.')
    else
      render :edit
    end
  end

  def destroy
    authorize @room
  end

  def join
    room = Room.find(params[:id])
    return redirect_to :back, alert: t('alert.rooms.not_exist') unless room
    return redirect_to :back, alert: t('alert.rooms.not_joinbale') unless room.joinable? current_user
    authorize room

    if room.users.include? current_user
      room.memberships.find_by(memberable: current_user)&.member!
    else
      room.users << current_user
      room.save
    end
    redirect_to room_path(room), notice: t('notice.rooms.joined')
  end

  def leave
    room = Room.find(params[:id])
    return redirect_to :back, alert: t('alert.rooms.not_exist') unless room
    return redirect_to :back, alert: t('alert.rooms.not_leaveable') unless room.leaveable? current_user
    authorize room

    room.users.delete current_user
    room.save
    return redirect_to room_path(room), notice: t('notice.rooms.leaved') if room.public?
    return redirect_to rooms_path, notice: t('notice.rooms.leaved') if room.private?
  end

  def invite
    room = Room.find(params[:id])
    return redirect_to :back, alert: t('alert.rooms.not_exist') unless room
    return redirect_to :back, alert: t('alert.rooms.not_invitable') unless room.invitable? current_user
    authorize room

    user_to_invite = Profile.find_by(screen_name: params[:invitation][:screen_name])&.user
    return redirect_to :back, alert: t('alert.users.not_exist') unless user_to_invite

    if room.users.include? user_to_invite
      membership = room.memberships.find_by(memberable: user_to_invite)
      # Already have membership
      if membership.administrator? || membership.maintainer? || membership.member?
        return redirect_to :back, alert: t('alert.memberships.already_member')
      # Already invited
      else
        return redirect_to :back, alert: t('alert.memberships.already_invited')
      end
    else
      room.invited_users << user_to_invite
      room.save
    end
    redirect_to room_path(room), notice: t('notice.rooms.invited')
  end

  private
  def room_params
    params.require(:room).permit(:screen_name, :display_name, :description, :private)
  end

  def set_room
    @room = Room.find(params[:id])
    authorize @room
  end

  def set_room_by_screen_name
    @room = Room.find_by(screen_name: params[:screen_name])
    authorize @room
  end

end

app/views/rooms/_form.html.slim
.panel.panel-default
  .panel-body
    = simple_form_for(room) do |f|
      = f.error_notification
      = f.input :display_name
      = f.input :screen_name
      = f.input :description
      = f.input :private, as: :boolean, wrapper: :vertical_boolean
      = f.button :submit, class: 'btn btn-primary'

app/views/rooms/edit.html.slim
.page-header
  h1= t('.editing_room')

== render 'form', room: @room

.btn-group
  = link_to t('back'), @room, class: 'btn btn-default'

app/views/rooms/index.html.slim
.page-header
  h1= t('Listing rooms')

= simple_form_for(:search) do |f|
  = f.error_notification
  = f.input :keyword, label: false

table.table.table-bordered.table-striped.table-condensed
  thead
    tr
      th Room
      th Description
      th Members

  tbody
    - @rooms.each do |room|
      tr
        td= link_to room.screen_name, room_path(room)
        td= simple_format room.description
        td
          - room.users.each do |user|
            = link_to image_tag(attachment_url(user&.profile, :avatar, :fill, 18, 18, format: 'png', fallback: 'default_avatar_18.png')), profile_path(user.profile), class: 'popover-userinfo', data: { title: user.screen_name, content: "Hi, I'm #{user.screen_name}." }


- if current_user
  = link_to t('New Room'), new_room_path, class: 'btn btn-primary'

app/views/rooms/new.html.slim
.page-header
  h1= t('.new_room')

== render 'form', room: @room

.btn-group
  = link_to t('back'), rooms_path, class: 'btn btn-default'

app/views/rooms/show.html.slim
h1= @room.display_name


.panel.panel-default
  .panel-body
    = simple_format @room.description
  table.table.table-bordered
    tbody
      tr
        th.col-sm-2= t('members')
        td= @room.users.size
      tr
        th= t('messages')
        td= @room.messages.size
      tr
        th= t('bots')
        td= @room.bots.size

.row.voffset-bottom20
  .col-sm-12
    - if current_user
      - if @room.joinable? current_user
        = link_to join_room_path(@room), method: :post, class: 'btn btn-primary btn-block' do
          = icon('plug', t('.join_this_room'))
      - if @room.chattable? current_user
        = link_to leave_room_path(@room), method: :post, class: 'btn btn-danger btn-block' do
          = icon('minus-square', t('.leave_this_room'))
      - if @room.invited? current_user
        = link_to leave_room_path(@room), method: :post, class: 'btn btn-danger btn-block' do
          = icon('minus-square', t('.cancel_invited'))

- if @room.invitable? current_user
  .row.voffset-bottom20
    .col-sm-12
      .panel.panel-default
        .panel-heading ユーザーを招待する
        .panel-body
          = simple_form_for(:invitation, url: invite_room_path(@room)) do |f|
            = f.input :screen_name, wrapper: :vertical_input_group do
              .input-group-addon @
              = f.input_field :screen_name, required: true, autofocus: true, class: 'form-control', placeholder: 'screen_name'
            .form-actions
              = f.button :submit, "Invite", class: 'btn btn-primary'


.row
  .col-sm-12
    - Membership.authorities.keys.each do |authority|
      .panel.panel-default
        .panel-heading
          = t(authority.pluralize.downcase)
          span.badge.badge-default.pull-right= @room.send("#{authority}_users").size
        .panel-body
          - @room.send("#{authority}_users").each do |user|
            = link_to image_tag(attachment_url(user&.profile, :avatar, :fill, 48, 48, format: 'png', fallback: 'default_avatar_48.png')), profile_path(user&.profile), class: 'popover-userinfo', data: { title: user.display_name, content: "Hi, I'm #{user.display_name}." }
    .panel.panel-default
      .panel-heading
        = t('bots')
        span.badge.badge-default.pull-right= @room.bots.size
      .panel-body
        - @room.bots.each do |bot|
          = link_to image_tag(attachment_url(bot&.profile, :avatar, :fill, 48, 48, format: 'png', fallback: 'default_avatar_48.png')), bot_path(bot), class: 'popover-botinfo', data: { title: bot.display_name, content: "Hi, I'm #{bot.display_name}." }
    .btn-group
      - if @room.has_member?(current_user) && @room.maintainable?(current_user)
        = link_to t('manage'), edit_room_path(@room), class: 'btn btn-default'
      = link_to t('back'), rooms_path, class: 'btn btn-primary'