config/routes.rb
Rails.application.routes.draw do
  get '/@:screen_name' => 'profiles#show_friendly', as: :profile_friendly
  resources :profiles, only: [ :show ]
  resource :profile, only: [ :edit, :update ]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :bots
  post '/rooms/join/:id' => 'rooms#join', as: :join_room
  post '/rooms/leave/:id' => 'rooms#leave', as: :leave_room
  post '/rooms/invite/:id' => 'rooms#invite', as: :invite_room
  get '/r/*screen_name' => 'rooms#show_friendly', as: :room_friendly, screen_name: %r`(?:[a-z0-9_-]+/)?[a-z0-9_-]+`
  resources :rooms
  resources :access_tokens, except: [ :show ]

  root to: 'pages#index'

  # Auth
  get '/auth/:privider/callback' => 'sessions#create'
  post '/auth/:privider/callback' => 'sessions#create'
  get '/sign_out' => 'sessions#destroy', as: :signout

  # API
  mount API::Root => '/api/'
  mount GrapeSwaggerRails::Engine => '/apidoc'

  # ActionCable
  mount ActionCable.server => '/cable'
end

app/views/layouts/_navigation.slim
.navbar-header
  button.navbar-toggle.collapsed[ type="button" data-toggle="collapse" data-target=".navbar-collapse" ]
    span.sr-only Toggle navigation
    span.icon-bar
    span.icon-bar
    span.icon-bar
  a.navbar-brand[ href="/" ] kokoro.io
.navbar-collapse.collapse
  ul.nav.navbar-nav.navbar-right
    - if current_user
      li= link_to rooms_path, target: '_blank' do
        = icon :comments, t('menu.rooms')
    li= link_to '/apidoc', target: '_blank' do
      = icon :book, t('menu.api-document')
    li= link_to '#' do
      = icon :question, t('menu.help')
    - if current_user
      li.dropdown
        a.dropdown-toggle[href="#" data-toggle="dropdown"]
          - if current_user.profile
            = image_tag attachment_url(current_user.profile, :avatar, :fill, 18, 18, format: 'png', fallback: 'default_avatar_18.png')
            '
            = current_user.profile&.screen_name
          - else
            = current_user.email
          b.caret
        ul.dropdown-menu
          li.dropdown-header= t('Bot')
          li= link_to bots_path do
            = icon :code, t('bots')
          li.dropdown-header= t('account')
          - if current_user.profile
            li= link_to profile_path(current_user.profile) do
              = icon :user, t('your_profile')
          li= link_to edit_profile_path do
            = icon :edit, t('edit_your_profile')
          li= link_to edit_registration_path(current_user) do
            = icon :edit, t('edit_your_account')
          li= link_to access_tokens_path do
            = icon :key, t('access_tokens')
          li.divider
          li= link_to destroy_user_session_path, method: :delete do
            = icon :'sign-out', t('auth.sign_out')
    - else
      li= link_to new_user_session_path do
        = icon('sign-in', t('auth.sign_in'))
      li= link_to new_user_registration_path do
        = icon('user-plus', t('auth.sign_up'))
  /form.navbar-form.navbar-right
  /  input.form-control[ type="text" placeholder="Search..." ]

app/views/layouts/application.slim
doctype html
html[ lang="ja" ]
  head
    meta[ charset="utf-8" ]
    meta[ http-equiv="X-UA-Compatible" content="IE=edge" ]
    meta[ name="viewport" content="width=device-width, initial-scale=1" ]
    title kokoro.io
    link rel="stylesheet" media="all" href="/stylesheets/application.css" data-turbolinks-track="true"
    script src="/javascripts/application.js" data-turbolinks-track="true"
    = csrf_meta_tags
  body
    .navbar.navbar-default.navbar-fixed-top[ role="navigation" ]
      .container
        = render partial: '/layouts/navigation'
    .container
      = render partial: '/application/flash_messages', flash: flash
      = yield

app/views/layouts/chat.slim
doctype html
html[ lang="ja" ]
  head
    meta[ charset="utf-8" ]
    meta[ http-equiv="X-UA-Compatible" content="IE=edge" ]
    meta[ name="viewport" content="width=device-width, initial-scale=1" ]
    meta[ name="action-cable-url" content="/cable" ]
    meta[ name="access-token" content=@access_token.token ]
    title kokoro.io
    link rel="stylesheet" media="all" href="/stylesheets/application.css" data-turbolinks-track="true"
    link rel="stylesheet" media="all" href="/stylesheets/chat.css" data-turbolinks-track="true"
    link rel="stylesheet" media="all" href="/stylesheets/gh.css"
    script src="/javascripts/application.js" data-turbolinks-track="true"
    script src="/javascripts/chat.js" data-turbolinks-track="true"
    = csrf_meta_tags
  body
    .navbar.navbar-default.navbar-fixed-top[ role="navigation" ]
      .container-fluid
        = render partial: '/layouts/navigation'
    .container-fluid
      = yield